# AppVeyor documentation https://www.appveyor.com/docs
configuration:
  - Release

assembly_info:
  patch: false

# Build script
version: '{build}'

image: Previous Visual Studio 2017
os: Previous Visual Studio 2017

# branches to build
branches:
  # whitelist
  only:
    - master
    - dev

clone_depth: 1
environment:
  global:
    # Set the DOTNET_SKIP_FIRST_TIME_EXPERIENCE environment variable to stop wasting time caching packages
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    # Disable sending usage data to Microsoft
    DOTNET_CLI_TELEMETRY_OPTOUT: true
  gh_token:
    secure: tlnq8XIYBO8uf9X6Umt0ei09ldGB7E9hhxT8gLxsfm4fnt2ymz8M2uMVtA0jplPj
    
pull_requests:
  # Do not increment build number for pull requests
  do_not_increment_build_number: true
 
nuget:
  # Do not publish NuGet packages for pull requests
  disable_publish_on_pr: true

init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true

install:
  # .NET Core SDK binaries
  - ps: $urlCurrent = "https://download.microsoft.com/download/8/8/5/88544F33-836A-49A5-8B67-451C24709A8F/dotnet-sdk-2.1.300-win-x64.zip"
  - ps: $env:DOTNET_INSTALL_DIR = "$pwd\.dotnetsdk"
  - ps: mkdir $env:DOTNET_INSTALL_DIR -Force | Out-Null
  - ps: $tempFileCurrent = [System.IO.Path]::Combine([System.IO.Path]::GetTempPath(), [System.IO.Path]::GetRandomFileName())
  - ps: (New-Object System.Net.WebClient).DownloadFile($urlCurrent, $tempFileCurrent)
  - ps: Add-Type -AssemblyName System.IO.Compression.FileSystem; [System.IO.Compression.ZipFile]::ExtractToDirectory($tempFileCurrent, $env:DOTNET_INSTALL_DIR)
  - ps: $env:Path = "$env:DOTNET_INSTALL_DIR;$env:Path"

#---------------------------------#
#       build configuration       #
#---------------------------------#
before_build:
  # Display .NET Core version
  - cmd: dotnet --version
  - choco install codecov
build_script:
  - ps: .\build.ps1 --verbosity=diagnostic
  - codecov -f .\artifacts\Coverage\coverage.xml -t $(CODECOV_TOKEN)

after_build:
  # For once the build has completed

on_finish :
  # any cleanup in here

#---------------------------------#
#       tests configuration       #
#---------------------------------#

test: off

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
# Store NuGet packages
- path: .\Artifacts\**\*.nupkg
  name: NuGet
# Store xUnit Test Results
- path: .\Artifacts\**\*.trx
  name: xUnit Test Results


#---------------------------------#
#      deployment configuration   #
#---------------------------------#

deploy:
# Publish Github
-provider: GitHub
  description: 'Release description'
  provider: GitHub
  auth_token:
    secure: $env:gh_token # your encrypted token from GitHub
  artifact: .\Artifacts\**\*.nupkg # upload all NuGet packages to release assets
  draft: false
  prerelease: true
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: false        # deploy on tag push only
# Publish MyGet packages
- provider: NuGet
  name: development
  server: https://www.myget.org/F/courio-dev/api/v2/package
  api_key:
    secure: 9uzkCroixqPrC9das6F7wx42qI+xXhfz+L0Bu4XPwxmIh8f+UrZGUEBwvsOrKzeg
  skip_symbols: true
  on:
    # Only publish from the master branch
    branch: master
# Publish NuGet packages
- provider: NuGet
  name: production
  api_key:
    secure: hd7kH5D5DJr+IpC+9zAklVm9r5Pm0Ku0RbMaA7DmReouBhExmFBPTVe+rWtl9zRa
  on:
    # Only publish from the master branch
    branch: master
    # Only publish if the trigger was a Git tag
    # git tag v0.1.0-beta
    # git push origin --tags
    appveyor_repo_tag: true

#---------------------------------#
#      cache configuration        #
#---------------------------------#

cache:
- tools -> build.cake
- packages -> build.cake