# Build script
image: Visual Studio 2017
os: Visual Studio 2017
init:
  - git config --global core.autocrlf true

clone_depth: 1
environment:
  global:
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    DOTNET_CLI_TELEMETRY_OPTOUT: 1
  
version: '{build}'
 
pull_requests:
  # Do not increment build number for pull requests
  do_not_increment_build_number: true
 
nuget:
  # Do not publish NuGet packages for pull requests
  disable_publish_on_pr: true
 
environment:
  # Set the DOTNET_SKIP_FIRST_TIME_EXPERIENCE environment variable to stop wasting time caching packages
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  # Disable sending usage data to Microsoft
  DOTNET_CLI_TELEMETRY_OPTOUT: true
 
build_script:
- ps: .\build.ps1
 
test: 'off'
deploy: 'off'