language: csharp
os:
  - osx
  - linux

# Ubuntu 14.04
sudo: required
dist: trusty
addons:
  apt:
    packages:
    - gettext
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8
    - zlib1g

# OS X 10.12
osx_image: xcode9.2

# Ensure Mono is installed
mono:
  - latest

# dotnet: 2.1.300-preview1-008174
dotnet: 2.1.4
# sudo apt-get install apt-transport-https
# sudo apt-get update
# sudo apt-get install dotnet-sdk-2.1.300-preview2-008533

env:
    # Set the DOTNET_SKIP_FIRST_TIME_EXPERIENCE environment variable to stop wasting time caching packages
  - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
    # Disable sending usage data to Microsoft
  - DOTNET_CLI_TELEMETRY_OPTOUT=true

before_install:
  - git fetch --depth=1
  # You must run this command to give Travis permissions to execute the build.sh shell script:
  - chmod +x build.sh
  
script:
  - ./build.sh --verbosity=diagnostic

cache:
  directories:
    - .packages
    - tools/Addins
    - tools/gitreleasemanager
    - tools/GitVersion.CommandLine